### ISSUE TITLE
Loading db ip into repository

### ISSUE THREAD

**Issue by benheart** [ankushs92/Spring-Boot-DB-IP#1]
It is very slow to run application, the log print "Loading db ip into repository", does it matter?

**Comment by ankushs92** [comment]
So this is how it works.
The entire csv file is loaded into the JVM into a TreeMap ,which is an indexed based Data structure.Now , you need to allocate more heap space to  your IDE(Eclipse or IntelliJ) .About 3 GB would suffice. 
If you don't allocate this much space, then the JVM would keep on garbage collecting while the file is still being loaded.This is what makes the load slow.
When you do this, and run the app,it would load within 10-15 seconds. 
Coming to the "Loading db ip into repository" part ,all you need to do is go to application.properties and add the following line  : 
logging.level.in.ankushs=INFO 
It would then stop printing debug information.
Let me know if you need more help to set it up.

For more detailed instructions,follow this blog post 
http://ankushs92.github.io/libraries/2016/05/12/java-db-ip.html

**Comment by benheart** [comment]
@ankushs92 Thanks for your timely reply. I allocate more heap space(3G) to my IDEA, and the app run successfully, but still very slowly. And I hava another question: why country from GeoEntity is country name(China) not country code(CN) ,i find it is country code(CN) in csv file. So i doubt is there CountryEnum or StateEnum to finish this convert?

**Comment by ankushs92** [comment]
Thats weird.It runs absolutely smoothly on my Macbook with 8 GB RAM. Are you saying that the 'ip resolving to a GeoEntity' is slow or the entire loading process is slow ? 

Also, I decided the skip the Country code altogether as I didn't see any point to it .Usually ,I prefer knowing the full Country name instead of the ISO name for it.
You can put it under the features section as enhancement,and I can do it whenever I have time.Can't promise though.

**Comment by benheart** [comment]
The entire loading process is slow . And my PC also with 8 GB RAM, but disk is HDD not SDD.This is JVM setting in IDEA:
-Xms3000m
-Xmx3000m
-XX:MaxPermSize=1024m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow

Just like you said, to get Country code or State code from GeoEntity could be a features section as enhancement, this would meet needs of other people. For me ,I want to give State code to front end. Anyway ,thank you very much.
